# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac


/run/initialize
/gps/particle proton
#/gps/ang/type iso
/gps/energy 500 MeV
/gps/position 0.0 0.0 -2.8 m
/gps/direction 0. 0. 1.
/run/beamOn 1
